export default {
  locale: 'ru',
  messages: {
    siteTitle: 'Personoj',
    switchLanguage: 'Switch Language',
    userLogin: 'Электронный адресс',
    userPassword: 'Пароль',
    registrationForm: 'Регистрация',
    registration: 'Зарегастрироваться',
    loginForm: 'Вход',
    enter: 'Войти',
    personList: 'Физ лица',
    person: 'Физ лицо',
    personAttributeList: 'Реквизиты физ лиц',
    name: 'Наименование',
    type: 'Тип',
    values: 'Значение',
    localizationLabel: 'Описание',
    allowArbitraryValues: 'Разрешить занчения не из списка',
    needApproval: 'Необходимо подтверждение',
    save: 'Сохранить',
    string: 'Строка',
    number: 'Номер',
    date: 'Дата',
    boolean: 'Логический',
    users: 'Пользователи'
  },
};
