export default {
  locale: 'ua',
  messages: {
    siteTitle: 'MERN blog de démarrage',
    switchLanguage: 'Changer de langue',
    userLogin: 'Електронна адреса',
    userPassword: 'Пароль',
    registrationForm: 'Реєстрація',
    registration: 'Зареєструватись',
    loginForm: 'Вхід',
    enter: 'Увійти',
    personList: 'Громадяни',
    personAttributeList: 'Реквізити фіз осіб',
    name: 'Найменування',
    type: 'Тип',
    values: 'Значення',
    localizationLabel: 'Опис',
    allowArbitraryValues: 'Дозволити значення, які не в списку',
    needApproval: 'Необхідне підтвердження',
    save: 'Зберегти',
  },
};
