export default {
  locale: 'ua',
  messages: {
    siteTitle: 'Personoj',
    switchLanguage: 'Changer de langue',
    userLogin: 'Електронна адреса',
    userPassword: 'Пароль',
    registrationForm: 'Реєстрація',
    registration: 'Зареєструватись',
    loginForm: 'Вхід',
    enter: 'Увійти',
    personList: 'Фіз особи',
    person: 'Фіз особа',
    personAttributeList: 'Реквізити фіз осіб',
    name: 'Найменування',
    type: 'Тип',
    values: 'Значення',
    localizationLabel: 'Опис',
    allowArbitraryValues: 'Дозволити значення, які не в списку',
    needApproval: 'Необхідне підтвердження',
    save: 'Зберегти',
    string: 'Строка',
    number: 'Номер',
    date: 'Дата',
    boolean: 'Логічний',
    users: 'Користувачі'
  },
};
